sudo: required
services:
  - docker

# Tag the image so we can refer it later since we cannot copy the image id returned by build command
# Creating image only for web project to run tests
# We should ideall run tests on all sub-projects
before_install:
  - docker build -t vaibhavdesai137/multi-containers-workflow-webapp -f ./web-app/Dockerfile.dev ./web-app
  # - docker build other-project-1
  # - docker build other-project-2

# Use the hyphens to terminate tests else "npm run test" will wait for user inputs
script:
  # For whatever reason, travis hangs with this after executing tests
  # - docker run vaibhavdesai137/multi-containers-workflow-webapp npm run test -- --coverage --forceExit
  - docker run -e CI=true vaibhavdesai137/multi-containers-workflow-webapp npm run test -- --watchAll=false

# We need all images for prod so lets do that here
# After building, upload to docker hub
after_success:
  # Build images
  - docker build -t vaibhavdesai137/multi-containers-workflow-workerapp -f ./worker-app/Dockerfile.prod ./worker-app
  - docker build -t vaibhavdesai137/multi-containers-workflow-apiapp -f ./api-app/Dockerfile.prod ./api-app
  - docker build -t vaibhavdesai137/multi-containers-workflow-webapp -f ./web-app/Dockerfile.prod ./web-app
  - docker build -t vaibhavdesai137/multi-containers-workflow-nginx -f ./nginx/Dockerfile.prod ./nginx
  # Login to docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Push to docker
  - docker push vaibhavdesai137/multi-containers-workflow-workerapp
  - docker push vaibhavdesai137/multi-containers-workflow-apiapp
  - docker push vaibhavdesai137/multi-containers-workflow-webapp
  - docker push vaibhavdesai137/multi-containers-workflow-nginx

# Deploying to aws beanstalk
# Bucket is needed because travis will create a zip file and copy it over to aws
# Deploy only when on "master" branch
# Access & Secret keys are stored as env in travis settings
deploy:
  provider: elasticbeanstalk
  region: "us-west-1"
  app: "multi-containers-workflow"
  env: "MultiContainersWorkflow-env"
  bucket_name: "elasticbeanstalk-us-west-1-849572186676"
  bucket_path: "multi-containers-workflow"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"